
#Incinerator's Try Hard Config
["The Incinerator"]
	#Range: 1 ~ 100
	"Charging time (ticks) of The Incinerator" = 60
	#Range: 1 ~ 100
	"(Client Only) Max Charging time (ticks) to Form the Biggest Magic Circle underfoot when charging" = 60
	#Range: 0.0 ~ 1.7976931348623157E308
	"Basic Damage dealt by The Incinerator's Skill" = 6.0
	#Range: 0.0 ~ 100.0
	"Max Health Damage Percentage dealt by The Incinerator's Skill" = 2.0
	#Range: 0.0 ~ 100.0
	"The Radius of the ignis circles released by The Incinerator's Skill" = 1.0

["The Immolator"]
	#Range: 1 ~ 100
	"Charging time (ticks) of The Immolator" = 45
	#Range: 1 ~ 100
	"(Client Only) Max Charging time (ticks) to Form the Biggest Magic Circle underfoot when charging" = 45
	#Range: 0.0 ~ 1.7976931348623157E308
	"Basic Ignis Circle Damage dealt by The Immolator's Skill" = 6.0
	#Range: 0.0 ~ 100.0
	"Max Health Damage Percentage dealt by The Immolator's Skill" = 2.0
	#Range: 0.0 ~ 100.0
	"The Radius of the ignis circles released by The Immolator's Skill" = 2.5
	#Range: 0.01 ~ 250.0
	"[Questionable, maybe unused method] The Radius of the Quake released by The Immolator's Skill" = 6.0
	#Range: 0.01 ~ 1.7976931348623157E308
	"[Questionable, maybe unused method] Quake Damage Multiplier of The Immolator's Skill" = 2.0

["Tidal Claws"]
	#Range: 0.0 ~ 1.7976931348623157E308
	"Tentacle Damage released by Tidal Claws" = 3.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Tentacle's First Detection Range released by Tidal Claws" = 16.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Tentacle's Second Detection Range released by Tidal Claws" = 16.0
	#Range: 0.01 ~ 1.7976931348623157E308
	"Hook's Max Range released by Tidal Claws" = 30.0
	#Range: 0.01 ~ 1.7976931348623157E308
	"Hook's Max Speed released by Tidal Claws" = 12.0

["Gauntlet of Bulwark"]
	#Range: 1.0 ~ 1.7976931348623157E308
	"Charge Damage Multiplier Of Gauntlet Of Bulwark" = 1.2

["Bloom Stone Pauldrons"]
	#Range: > 1
	"Cooldown time (ticks) of Bloom Stone Pauldrons to shoot Amethyst Cluster" = 240

["The Annihilator"]
	#Range: 0.01 ~ 1.7976931348623157E308
	"Skill Range Of The Annihilator" = 6.0
	#Range: 0.01 ~ 1.7976931348623157E308
	"Skill Damage Multiplier Of The Annihilator" = 2.0
	#Range: 1 ~ 1000
	"Charging time (ticks) of The Annihilator" = 40
	#Range: > 1
	"Skill Cooldown time (ticks) of The Annihilator" = 100

["Gauntlet of Guard"]
	#Range: 0.01 ~ 1.7976931348623157E308
	"Attraction Radius Of Gauntlet Of Guard" = 11.0
	#Range: 0.01 ~ 1.7976931348623157E308
	"Scale of Normalized Attraction Vector Of Gauntlet Of Bulwark" = 0.1

["Cursed Bow"]
	"Whether Cursed Bow can be enchanted on Enchantment Table, and with Infinity and Flaming Arrow" = true

["Cursium Armor"]
	#Range: > 1
	"Skill Cooldown time (ticks) of Cursium Helmet" = 200
	#Range: > 1
	"Skill Cooldown time (ticks) of Cursium Boots" = 200
	#Range: -1919810.0 ~ 1919810.0
	"Skill Speed of Cursium Boots" = -1.7999999523162842

[Ignitium_Armor]
	#Range: > 1
	"Skill Cooldown time (ticks) of Ignitium Helmet" = 300

[Ceraunus]
	#Range: 0.05 ~ 10.0
	"Ceraunus Charging Time (Seconds)" = 0.5
	#Range: 1 ~ 360
	"Number Of Ceraunus Waves" = 4
	#Range: 1 ~ 3600
	"Life Time (ticks) Of Ceraunus Waves" = 60
	#Range: 0.01 ~ 15.0
	"Velocity of Thrown Ceraunus" = 2.5

[Astrape]
	#Range: 0.05 ~ 10.0
	"Astrape Charging Time (Seconds)" = 0.5
	#Range: 0.01 ~ 114514.0
	"Astrape Lightning Acceleration Power" = 0.15
	#Range: 0.0 ~ 256.0
	"Astrape Lightning Area Radius" = 1.0

["Laser Gatling"]
	"Whether Laser Gatling can ignite blocks when used by the player" = true
	#Controls the speed multiplier of laser beam entities.
	#This only affects lasers that have an owner and are NOT fired by The Harbinger.
	#Range: 0.01 ~ 100.0
	"laser Speed Multiplier" = 1.0

